# Generated by Django 4.2.5 on 2023-09-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdoc', '0010_makeappointment_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeappointment',
            name='appDate',
            field=models.CharField(max_length=100),
        ),
    ]
