# Generated by Django 4.2.5 on 2023-09-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdoc', '0012_makeappointment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeappointment',
            name='iswaiting',
            field=models.BooleanField(default=True),
        ),
    ]
